name: news_app
description: News App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  equatable: ^2.0.3
  timeago: ^3.2.2
  flutter_html: ^2.2.1
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
